export const Quoter = {
  codeBuilder: {
    color: {
      aalto: 'Aal',
      almendra: 'Alm',
      antracita: 'Ant',
      aqua: 'Aqu',
      arce: 'Arc',
      arena: 'Are',
      blancoDicks: 'BlD',
      brechiato: 'Bre',
      california: 'Cal',
      celadon: 'Cel',
      ceppoClaro: 'CCl',
      ceppoOscuro: 'COs',
      cobre: 'Cob',
      coral: 'Cor',
      crudo: 'Cru',
      cumelen: 'Cum',
      dalmata: 'Dal',
      domuyo: 'Dom',
      dorado: 'Dor',
      dustyMauve: 'DMa',
      fitzRoy: 'FRo',
      frey: 'Fre',
      grafito: 'Gra',
      gris: 'Gri',
      grisCemento: 'GCe',
      grisDicks: 'GDi',
      grisPerla: 'GPe',
      gropius: 'Gro',
      guggenheim: 'Gug',
      hueso: 'Hue',
      lanin: 'Lan',
      londres: 'Lon',
      marrakesh: 'Mar',
      mercurio: 'Mer',
      mies: 'Mie',
      mostaza: 'Mos',
      napoleon: 'Nap',
      naranja: 'Nar',
      natural: 'Nat',
      nubes: 'Nub',
      paine: 'Pai',
      petroleo: 'Pet',
      plata: 'Pla',
      pluton: 'Plu',
      pucon: 'Puc',
      puelo: 'Pue',
      rio: 'Rio',
      rosa: 'Ros',
      salmon: 'Sal',
      taupe: 'Tau',
      tulum: 'Tul',
      venus: 'Ven',
      verdeAlpes: 'Neg',
      negroAlpes: 'Neg',
      yacones: 'Yac',
      llaoLlao: 'Lla',
      boana: 'Boa',
      sitana: 'Sit',
      geko: 'Gek',
      cururu: 'Cur',
      komodo: 'Kom',
      caraguay: 'Car',
      oliva: 'Oli',
      niebla: 'Nie',
      ceniza: 'Cen',
      ocaso: 'Oca',
      avena: 'Ave',
      bali: 'Bal',
      terracota: 'Ter',
      acero: 'Ace',
    },
    dim: {
      '10x10': '1010',
      '10x40': '1040',
      '12x50': '1250',
      '13x60': '1360',
      '20x40': '2040',
      '40x40': '4040',
      '50x50': '5050',
      '60x40': '4060',
      canto_visto: '4040',
      escalon: '4040',
      zocalo: '1040',
    },
    forma: {
      '13 x 60': '136',
      '60 x 40': 'Los',
      '64 panes': '64P',
      'Piso tecnico': 'PtD',
      'Pisos Elevados': 'PtD',
      'Pisos elevados': 'PtD',
      'Placas de terrazo': 'Dur',
      Plinth: 'Zoc',
      'Terrazzo raised floor': 'PtD',
      'Terrazzo tiles': 'Dur',
      Zocalos: 'Zoc',
      // nuevas variables para colecciones
      volcan: 'Dur',
      splash: 'Dur',
      elementos: 'Dur',
      chromatic: 'Dur',
      clasica: 'Dur',
      gradiente: 'Dur',
      rusticato: 'Dur',
      '12x50': 'Dur',
      raisedFloors: 'PtD',
    },
  },
  colorForm: {
    actionDesktop: {
      en: 'Right click over blends to zoom',
      es: 'Click derecho sobre los blends para agrandar',
    },
    actionMobile: {
      en: 'Press 1 second over blends to zoom',
      es: 'Presiona 1 segundo sobre los blends para agrandar',
    },
    label: {
      en: 'Selected blend',
      es: 'Blend elegido',
    },
  },
  contactForm: {
    email: {
      en: 'Email',
      es: 'Email',
    },
    emailHint: {
      en: 'We will send you the quote to this address',
      es: 'Enviaremos el presupuesto a esta direccion',
    },
    label: {
      en: 'Contact data',
      es: 'Datos de contacto',
    },
    name: {
      en: 'Name & Surname',
      es: 'Nombre & Apellido',
    },
    nameHint: {
      en: 'Please give us your full name 😀',
      es: 'Por favor decinos tu nombre completo 😀',
    },
    phone: {
      en: 'Phone',
      es: 'Teléfono',
    },
  },
  productForm: {
    label: {
      en: 'Product',
      es: 'Producto',
    },
    paverOpt: ['64 panes', '60 x 40', '13 x 60'],
    plinthOpt: ['9.5 x 40 x 1.8'],
    prodArray: {
      en: ['Terrazzo tiles', 'Terrazzo raised floor', 'Pavers', 'Plinths'],
      es: ['Placas de terrazo', 'Pisos elevados', 'Losetas', 'Zocalos'],
    },
    product: {
      en: 'Product',
      es: 'Producto',
    },
    size: {
      en: 'Size (cm)',
      es: 'Dimensión (cm)',
    },
    type: {
      en: 'Type',
      es: 'Tipo',
    },
  },
  quantityForm: {
    enableSides: {
      en: 'Not sure how many m2 there are',
      es: 'No estoy seguro cuantos m2 son',
    },
    excess: {
      en: 'Excess',
      es: 'Desperdicio',
    },
    excessHint: {
      en: '% of excess material',
      es: '% de material en exceso',
    },
    label: {
      en: 'Quantity',
      es: 'Cantidad',
    },
    quantity: {
      en: 'Quantity',
      es: 'Cantidad',
    },
    side1: {
      en: 'Side 1',
      es: 'Lado 1 (metros)',
    },
    side2: {
      en: 'Side 2',
      es: 'Lado 2 (metros)',
    },
    sidesLabelm2: {
      en: 'Tell us the measurements of the sides of the sector to be covered',
      es: 'Indicanos las medidas de los lados del sector a cubrir',
    },
  },
};
