export const CODES = {
  AR: 'es',
  CL: 'es',
  UY: 'es',
  VE: 'es',
  GB: 'en',
  CA: 'en',
  US: 'en',
  CR: 'es',
  GT: 'es',
  MX: 'es',
  ES: 'es',
  PY: 'es',
  PE: 'es',
  BO: 'es',
  CO: 'es',
};

export const DefaultLangObj = {
  ip: '190.17.99.131',
  registry: 'LACNIC',
  countrycode: 'AR',
  countryname: 'Argentina',
  asn: {
    code: '10318',
    name: 'Telecom Argentina S.A.',
    route: '190.17.96.0/19',
    start: '190.17.96.0',
    end: '190.17.127.255',
    count: '8192',
  },
  spam: false,
  tor: false,
  city: 'Buenos Aires',
};
