export const MENU = {
  local: [
    {
      en: 'Collections',
      es: 'Colecciones',
      url: { es: 'colecciones', en: 'collections' },
      header: true,
      footer: false,
      sideMenu: true,
      submenu: true,
    },
    {
      en: 'Samples',
      es: 'Muestras',
      url: { es: 'muestras', en: 'samples' },
      header: true,
      footer: false,
      sideMenu: true,
      submenu: false,
    },
    {
      en: 'Lookbook',
      es: 'Inspiracion',
      url: { es: 'inspiracion', en: 'lookbook' },
      header: true,
      footer: false,
      sideMenu: true,
      submenu: false,
    },
    {
      en: 'Blog',
      es: 'Blog',
      url: { es: 'blog', en: 'blog' },
      header: true,
      footer: false,
      sideMenu: true,
      submenu: false,
    },
    {
      en: 'Contact us',
      es: 'Contacto',
      url: { es: 'contacto', en: 'contact' },
      header: false,
      footer: true,
      sideMenu: false,
      submenu: false,
    },
    {
      en: 'Returns & Shipping',
      es: 'Devoluciones & Envíos',
      url: { es: 'info/devoluciones-envios', en: 'info/returns-shipping' },
      header: false,
      footer: true,
      sideMenu: false,
      submenu: false,
    },
    {
      en: 'Terms of service',
      es: 'Términos y condiciones ',
      url: { es: 'info/terminos-condiciones', en: 'info/terms-service' },
      header: false,
      footer: true,
      sideMenu: false,
      submenu: false,
    },
    {
      en: 'Privacy policy',
      es: 'Política de privacidad',
      url: { es: 'info/politica-privacidad', en: 'info/privacy-policy' },
      header: false,
      footer: true,
      sideMenu: false,
      submenu: false,
    },
  ],
  ext: [
    {
      en: 'Products',
      es: 'Productos',
      url: { es: 'colecciones/all', en: 'collections/all' },
      header: true,
      footer: false,
      sideMenu: true,
      submenu: false,
    },
    {
      en: 'Samples',
      es: 'Muestras',
      url: { es: 'muestras', en: 'samples' },
      header: true,
      footer: false,
      sideMenu: true,
      submenu: false,
    },
    {
      en: 'Lookbook',
      es: 'Inspiracion',
      url: { es: 'inspiracion', en: 'lookbook' },
      header: true,
      footer: false,
      sideMenu: true,
      submenu: false,
    },
    {
      en: 'Blog',
      es: 'Blog',
      url: { es: 'blog', en: 'blog' },
      header: true,
      footer: false,
      sideMenu: true,
      submenu: false,
    },
    {
      en: 'Contact us',
      es: 'Contacto',
      url: { es: 'contacto', en: 'contact' },
      header: false,
      footer: true,
      sideMenu: false,
      submenu: false,
    },
    {
      en: 'Returns & Shipping',
      es: 'Devoluciones & Envíos',
      url: { es: 'info/devoluciones-envios', en: 'info/returns-shipping' },
      header: false,
      footer: true,
      sideMenu: false,
      submenu: false,
    },
    {
      en: 'Terms of service',
      es: 'Términos y condiciones ',
      url: { es: 'info/terminos-condiciones', en: 'info/terms-service' },
      header: false,
      footer: true,
      sideMenu: false,
      submenu: false,
    },
    {
      en: 'Privacy policy',
      es: 'Política de privacidad',
      url: { es: 'info/politica-privacidad', en: 'info/privacy-policy' },
      header: false,
      footer: true,
      sideMenu: false,
      submenu: false,
    },
  ],
};
